### PR TITLE
Adding crypto challenges

### PR DESCRIPTION
**Pull request by Ariana1729**
Added BabyRSA and BabyRSA2
p.s. is it possible to add math to readme.md

### CODE REVIEW

**Comment by daniellimws** [comment]
I think the best way is to generate an image using
http://www.sciweavers.org/free-online-latex-equation-editor

**Review by daniellimws — APPROVED** [review]
nice :+1:!
not merging first in case you want to add equations

**Comment by Ariana1729** [comment]
Having in plaintext seems better than just dumping a bunch of svgs/pngs.
Should be able to merge

**Comment by daniellimws** [comment]
Ok

**Pull request merged**
